## NAME: PRANAV PRATYUSH
## REG NO: 21BAI10019

In [2]:
import numpy as np

#confusion matrix
conf_matrix = np.array([[296, 1, 0, 2],
                       [1, 97, 0, 0],
                       [0, 0, 15, 0],
                       [0, 0, 0, 20]])

def calculate_metrics(conf_matrix):
    
    overall_accuracy = np.trace(conf_matrix) / np.sum(conf_matrix)
    sensitivity = np.diagonal(conf_matrix) / np.sum(conf_matrix, axis=1)
    precision = np.diagonal(conf_matrix) / np.sum(conf_matrix, axis=0)
    f1_score = 2 * (precision * sensitivity) / (precision + sensitivity)

    return overall_accuracy, sensitivity, precision, f1_score

accuracy, sensitivity, precision, f1_score = calculate_metrics(conf_matrix)
# Display confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

# results
print("Overall Accuracy:", accuracy)
print("Sensitivity (Recall) for each class:", sensitivity)
print("Precision for each class:", precision)
print("F1 Score for each class:", f1_score)

Confusion Matrix:
[[296   1   0   2]
 [  1  97   0   0]
 [  0   0  15   0]
 [  0   0   0  20]]
Overall Accuracy: 0.9907407407407407
Sensitivity (Recall) for each class: [0.98996656 0.98979592 1.         1.        ]
Precision for each class: [0.996633   0.98979592 1.         0.90909091]
F1 Score for each class: [0.99328859 0.98979592 1.         0.95238095]
